title: Canal OnTheGo
iconURL: assets/default-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: billiamw0nner
  github: Teethew

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 1883
google_analytics: UA-NNNNNNNN-N
